### ISSUE TITLE
Publish the npm package

### ISSUE THREAD

**Issue by ghost** [lirantal/operations-orchestration-api#19]
Hi @lirantal ,
Don't forget to publish the new package (v2.0.0) on npm

**Comment by ghost** [comment]
After updating the README and other final stuffs

**Comment by lirantal** [comment]
Yep, waiting to update README and such.

**Comment by lirantal** [comment]
Published.

**Comment by ghost** [comment]
Great. Waiting for more contributions

**Comment by lirantal** [comment]
@Attrash-Islam if you're up to it, we can increase coverage, say here: 
![image](https://cloud.githubusercontent.com/assets/316371/25070542/22a8eaa8-22aa-11e7-88a1-14d2f7f62003.png)

**Comment by ghost** [comment]
Yes. I paid attention that errors is not tested. I'll try to create new scenarios in tests
