### ISSUE TITLE
Remove callbacks in favor of Promises

### ISSUE THREAD

**Issue by lirantal** [lirantal/operations-orchestration-api#2]
Due to the recent adoption of promises in core node and the ES2015 standard the library should be refactored to work with promises.

**Comment by ghost** [comment]
Or even with async/await and babel :wink:  ?

**Comment by lirantal** [comment]
Definitely :-)

If you weren't just dropping by, which I appreciate by itself, and you're using the OO API library then I would be very happy to see a PR on this subject.

**Comment by ghost** [comment]
I'd like to.. That's great opportunity! Thanks

**Comment by lirantal** [comment]
I'll be expecting it :)

**Comment by ghost** [comment]
I've started to refactor the code to use OOP, and after your code-review I'll continue with the async/await thing.. Give me a little more time :smile:

**Comment by lirantal** [comment]
Awesome!
Would love to see that, no pressure on time.

**Comment by ghost** [comment]
Waiting for your review :wink:

**Comment by lirantal** [comment]
@Attrash-Islam no worries, I saw this coming in but haven't had a chance yet to look.

Are you also working with OO to actually use the updated promise API with it?

**Comment by ghost** [comment]
Thanks for replaying @lirantal .
This initial commit regards OOP classes instead of _.extend usage

I thought of updating the callbacks in sake of async/await if you're interested. If you like the Promise API for performance or other favors I'll refactor to Promises. Waiting your signal :wink:

**Comment by lirantal** [comment]
Cool!

Like I said, I saw it coming in on my inbox but haven't had a chance to glance through the code.
Would be nice to convert callbacks to async/await, so you're more than welcome to work on that too. Give me a couple of days to get some free time to review the PR and I'll happily merge it in.

**Comment by ghost** [comment]
Got it. Thanks

**Comment by ghost** [comment]
**One important note**: Your test doesn't change, just the source, and all of them are passing.

This note because I'll need to modify them to fit with the new async/await syntax

**Comment by lirantal** [comment]
Fixed in #16 thanks to @Attrash-Islam
