### ISSUE TITLE
Adopt JavaScript Code Style / ESLint

### ISSUE THREAD

**Issue by lirantal** [lirantal/operations-orchestration-api#3]
Open for discussion but basically:
- Adopt JavaScript Code Style: https://github.com/feross/standard
- Adopt ESLint (https://github.com/xjamundx/eslint-plugin-standard)

**Comment by lirantal** [comment]
@Attrash-Islam want to take this one to add standardjs and re-format the code + add it as a lint rule to run in test?

**Comment by ghost** [comment]
If you're really interested in Linting then you must go with the most modern linter on earth :laughing: 

https://github.com/prettier/prettier
https://github.com/prettier/prettier-eslint-cli

**Comment by ghost** [comment]
Also liked https://standardjs.com/#usage

**Comment by lirantal** [comment]
Prettier looks nice but they don't support non semicolons right? it's a standard I'm trying to get used to and adopt across my projects.

The good thing about using standardjs is that when you adopt it and people contribute they already know your rules because using standardjs means you're aligned with a specific set of rules already and contributors don't need to learn your new rules.

**Comment by ghost** [comment]
Then, I'll adapt standardjs :+1:

**Comment by ghost** [comment]
Waiting for more issues :muscle:

**Comment by lirantal** [comment]
Fixed by #21
